{ Pixel and playback regressions. Fixtures are generated by our own script.
  SPDX-License-Identifier: 0BSD }
unit WebP_Checks;
{$mode objfpc}{$H+}
interface
procedure RunWebPChecks;
implementation
uses Classes, SysUtils, Graphics, IntfGraphics, FPImage, Forms, InkWebP, InkPage;

procedure Require(Value: Boolean; const Message: string);
begin if not Value then raise Exception.Create('WebP: '+Message) end;

function ReadBytes(const Name: string): TBytes;
var S: TFileStream;
begin
  Result := nil; S := TFileStream.Create(Name,fmOpenRead);
  try SetLength(Result,S.Size); if S.Size > 0 then S.ReadBuffer(Result[0],S.Size)
  finally S.Free end;
end;

procedure RunWebPChecks;
const Root = 'tests/fixtures/webp/';
var Manifest, Fields: TStringList; I,J,K,Frames,Tolerance,Offset,Loop: Integer;
    S: TMemoryStream; W: TInkWebP; Expected, Data: TBytes;
    Image: TLazIntfImage; Color: TFPColor; Name: string;
    Now: QWord; Page: TInkPage; Host: TForm;

  procedure CompareFrame(Frame: Integer);
  var C: array[0..3] of Byte; X,Y,K: Integer;
  begin
    Require(W.DecodeFrame(Frame),Name+' decodes frame '+IntToStr(Frame));
    Require(W.Decoded,Name+' reports decoded pixels');
    Image := W.Bitmap.CreateIntfImage;
    try
      for Y := 0 to W.Height-1 do for X := 0 to W.Width-1 do
      begin
        Color := Image.Colors[X,Y];
        C[0] := Color.Blue shr 8; C[1] := Color.Green shr 8;
        C[2] := Color.Red shr 8; C[3] := Color.Alpha shr 8;
        Offset := ((Frame*W.Height+Y)*W.Width+X)*4;
        for K := 0 to 3 do
          Require((Abs(Integer(C[K])-Integer(Expected[Offset+K])) <= Tolerance) and
            ((K <> 3) or (C[K] = Expected[Offset+K])),
            Format('%s frame %d pixel %d,%d channel %d: got %d, expected %d',
              [Name,Frame,X,Y,K,C[K],Expected[Offset+K]]));
      end;
    finally Image.Free end;
  end;

begin
  Manifest := TStringList.Create; Fields := TStringList.Create; S := TMemoryStream.Create;
  try
    Manifest.LoadFromFile(Root+'manifest.tsv');
    Fields.Delimiter := #9; Fields.StrictDelimiter := True;
    for I := 0 to Manifest.Count-1 do
    begin
      Fields.DelimitedText := Manifest[I]; Name := Fields[0];
      Frames := StrToInt(Fields[3]); Tolerance := StrToInt(Fields[4]);
      S.LoadFromFile(Root+Name+'.webp'); W := TInkWebP.Create(S);
      try
        Require(W.Valid,Name+' valid container');
        Require((W.Width=StrToInt(Fields[1])) and (W.Height=StrToInt(Fields[2])),Name+' dimensions');
        Require(W.FrameCount=Frames,Name+' frame count');
        Expected := ReadBytes(Root+Name+'.bgra');
        Require(Length(Expected)=W.Width*W.Height*Frames*4,Name+' oracle size');
        for J := 0 to Frames-1 do CompareFrame(J);
        if Frames > 1 then
        begin
          CompareFrame(1); CompareFrame(Frames-1); CompareFrame(0);
          Require((W.BackgroundAlpha=77) and (W.Loops=2),'animation metadata');
          W.Restart; Now := 1000;
          Require(not W.Advance(Now),'initial frame starts timing');
          for Loop := 1 to 2 do
            for J := 0 to Frames-1 do
            begin
              K := W.Frame(J).Duration; if K = 0 then K := 100;
              Inc(Now,K);
              Require(not W.Advance(Now-1),'does not advance early');
              if (Loop=2) and (J=Frames-1) then
                Require(not W.Advance(Now) and W.Finished,'finite loop ends on final frame')
              else Require(W.Advance(Now),'frame advances at deadline');
            end;
          Require(W.FrameIndex=Frames-1,'last frame retained');
          W.Restart; Require(not W.Finished and (W.FrameIndex=0),'restart resets loop state');
          Require(not W.Advance(1000),'restart arms timer');
          Require(W.Advance(1000000) and (W.FrameIndex=1),'stall decodes at most one frame');
        end;
        Require(not W.DecodeFrame(-1) and not W.DecodeFrame(Frames),'invalid frame indices');
      finally W.Free end;
    end;
    { Every prefix of a real file must reject its truncated RIFF body. }
    Data := ReadBytes(Root+'animation.webp');
    for I := 0 to High(Data) do
    begin
      S.Clear; if I > 0 then S.WriteBuffer(Data[0],I);
      W := TInkWebP.Create(S);
      try Require(not W.Valid and not W.Decoded,'truncated RIFF rejected') finally W.Free end;
    end;
    { HTML loading, alt fallback, and freeing/reloading the animation. }
    Host := TForm.Create(nil);
    Page := TInkPage.Create(Host);
    Page.Parent := Host;
    try
      Page.LoadHTML('<img src="'+ExpandFileName(Root+'animation.webp')+'" alt="animation">');
      Require(Page.ImageCount=1,'HTML image pipeline loads animated WebP');
      Require(Assigned(Page.Block(0).WebP) and Page.Block(0).WebP.Decoded,'HTML retains playback object');
      Page.LoadHTML('<img src="'+ExpandFileName(Root+'noise-lossless.webp')+'">');
      Require(Page.ImageCount=1,'HTML replacement loads still WebP');
    finally Host.Free end;
  finally S.Free; Fields.Free; Manifest.Free end;
  WriteLn('WebP pixel, animation, timing, truncation and HTML checks passed.');
end;
end.
