#!/usr/bin/env python3
"""Writes inkentities.inc: the HTML standard's named character references,
from the table Python ships (html.entities.html5), for InkDOM.

    python3 tools/make_entities.py > inkentities.inc
"""
from html.entities import html5

names = sorted({k[:-1] if k.endswith(';') else k for k in html5}, key=lambda s: s.encode())
print("{ The HTML standard's named character references, generated by")
print("  tools/make_entities.py - do not edit.  Legacy: also read without its")
print("  semicolon, as browsers do for the old Latin-1 names. }")
print("const")
print("  EntityCount = %d;" % len(names))
print("  Entities: array[0..EntityCount-1] of TNamedChar = (")
rows = []
for n in names:
    v = html5.get(n + ';', html5.get(n))
    legacy = n in html5
    val = ''.join('#$%02X' % b for b in v.encode('utf-8'))
    rows.append("    (N:'%s';V:%s;L:%s)" % (n, val, 'True' if legacy else 'False'))
print(',\n'.join(rows) + ');')
